### PR TITLE
Add AGPLv3 License

### PR DESCRIPTION
**Pull request by olivia-livs**
Should also make disclaimers at the start of each .gd file. That should be done by the project author.

### CODE REVIEW

**Comment by olivia-livs** [comment]
Example disclaimer for convenience:
```
# OpenSC4 - Open source reimplementation of Sim City 4
# Copyright (C) <year> <name of author>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.
```

**Review by TorchedSammy — COMMENTED** [review]
i think if you want to be the one to add the license, the least you could've done is run some script to add the heading to all source files as well

**Comment by olivia-livs** [comment]
> i think if you want to be the one to add the license, the least you could've done is run some script to add the heading to all source files as well

why do you have to be so rude?
Took longer than expected but I made a script for that
Change <year> and <author> because I didn't make this project so its not mine to license, I'm just trying to do the work for it.
```
#!/bin/bash                                                                                  
                                                                                             
# use newline characters '\n', in one line                                                   
disclaimer='# OpenSC4 - Open source reimplementation of Sim City 4\n# Copyright (C) <year> <name of author>\n#\n# This program is free software: you can redistribute it and/or modify\n# it under the terms of the GNU Affero General Public License as published by\n# the Free Software Foundation, either version 3 of the License, or\n# (at your option) any later version.\n#\n# This program is distributed in the hope that it will be useful,\n# but WITHOUT ANY WARRANTY; without even the implied warranty of\n# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the\n# GNU Affero General Public License for more details.\n#\n# You should have received a copy of the GNU Affero General Public License\n# along with this program. If not, see <https://www.gnu.org/licenses/>.\n\n'                                                        
                                                                                             
file_extension='.gd'                                                                         
                                                                                             
# check if the disclaimer is okay                                                            
echo -en $disclaimer                                                                         
                                                                                             
echo -en $disclaimer > temp && cat *$(echo $file_extension) >> temp && mv -T temp *$(echo $file_extension)                                                                                
echo -en $disclaimer > temp && cat */*$(echo $file_extension) >> temp && mv -T temp */*$(echo $file_extension)                                                                            
echo -en $disclaimer > temp && cat */*/*$(echo $file_extension) >> temp && mv -T temp */*/*$(echo $file_extension)                                                                        
echo -en $disclaimer > temp && cat */*/*/*$(echo $file_extension) >> temp && mv -T temp */*/*/*$(echo $file_extension)                                                                    
echo -en $disclaimer > temp && cat */*/*/*/*$(echo $file_extension) >> temp && mv -T temp */*/*/*/*$(echo $file_extension)                                                                
echo -en $disclaimer > temp && cat */*/*/*/*/*$(echo $file_extension) >> temp && mv -T temp */*/*/*/*/*$(echo $file_extension)                                                            
                                                                                             
rm temp 
```

**Review by AdrienJaguenet — COMMENTED** [review]
OK by me but I'd like @Wibbert's word

**Pull request closed without merging**
